export const t = {
  notAuthorized: "🚫 No estás autorizado. Usa /auth <contraseña> para pedir acceso.",
  adminOnly: "🚫 Solo el admin puede usar este comando.",
  authAlready: "Ya estás autorizado. Usa /help para ver los comandos.",
  authRevoked: "Tu acceso fue revocado. Habla con el admin.",
  authBadPassword: "Contraseña incorrecta.",
  authGranted: "✅ Acceso concedido. Usa /help para ver los comandos.",
  authUsage: "Uso: /auth <contraseña>",
  authUserGranted: (name) => `El usuario ${name} ahora tiene acceso al bot.`,
  help: [
    "🎬 /movie <nombre> — buscar y agregar una película",
    "📺 /serie <nombre> — buscar y agregar una serie",
    "/library [filtro] — ver la biblioteca (películas y series)",
    "/upcoming [días] — próximos estrenos y episodios (default 30)",
    "/clear — cancelar la operación en curso",
    "/help — esta ayuda",
  ].join("\n"),
  helpAdmin: [
    "",
    "*Admin:*",
    "/rss — sync RSS en ambos servicios",
    "/wanted — buscar todo lo faltante",
    "/refresh — refrescar bibliotecas",
    "/users — usuarios autorizados",
    "/revoke — revocar un usuario",
    "/unrevoke — restaurar un usuario",
    "/cid — ID de este chat",
  ].join("\n"),
  cid: (id) => `ID de este chat: \`${id}\``,
  cleared: "❌ Operación cancelada.",
  sonarrMissing: "Sonarr no está configurado.",
  movieUsage: "Uso: /movie <nombre de la película>",
  serieUsage: "Uso: /serie <nombre de la serie>",
  noResults: (term) => `No encontré nada para "${term}".`,
  foundN: (n, icon) => `${icon} Encontré ${n} resultado(s). Elige uno:`,
  alreadyAdded: (title) => `"${title}" ya está en la biblioteca.`,
  pickProfile: "Elige el perfil de calidad:",
  pickFolder: "Elige la carpeta de destino:",
  pickMonitor: "¿Qué temporadas monitorear?",
  searchNow: "¿Buscar y descargar ahora?",
  added: (icon, title) => `${icon} ✅ "${title}" agregada. ¡Listo!`,
  yes: "✔️ Sí",
  no: "✖️ No",
  cancel: "❌ Cancelar",
  usersTitle: "Usuarios autorizados:",
  noUsers: "No hay usuarios autorizados.",
  noRevoked: "No hay usuarios revocados.",
  revokeWho: "¿A quién revocar?",
  unrevokeWho: "¿A quién restaurar?",
  confirmRevoke: (name) => `¿Revocar el acceso de ${name}?`,
  confirmUnrevoke: (name) => `¿Restaurar el acceso de ${name}?`,
  revoked: (name) => `Acceso de ${name} revocado.`,
  unrevoked: (name) => `Acceso de ${name} restaurado.`,
  userNotFound: "usuario no encontrado",
  commandsSent: (list) => `✅ Comandos enviados:\n${list.join("\n")}`,
  libraryEmpty: "La biblioteca está vacía (o nada coincide con el filtro).",
  calendarEmpty: "Nada programado en ese rango.",
  error: (msg) => `⚠️ Error: ${msg}`,
};
