export const es = {
  locale: "es",
  notYourMenu: "⛔ Este menú es de otra persona.",
  notAuthorized: "🚫 No estás autorizado. Usa /auth <contraseña> para pedir acceso.",
  adminOnly: "🚫 Solo el admin puede usar este comando.",
  authAlready: "Ya estás autorizado. Usa /help para ver los comandos.",
  authRevoked: "Tu acceso fue revocado. Habla con el admin.",
  authBadPassword: "Contraseña incorrecta.",
  authGranted: "✅ Acceso concedido. Usa /help para ver los comandos.",
  authUsage: "Uso: /auth <contraseña>",
  authUserGranted: (name) => `El usuario ${name} ahora tiene acceso al bot.`,
  notifAvailable: (icon, title) => `${icon} ✅ ${title} ya está disponible`,
  notifEpisodes: (title, n, list) => `📺 ✅ ${title} — ${n} episodio(s) nuevos: ${list}`,
  help: [
    "🎬 /movie <nombre> — buscar y agregar una película",
    "📺 /serie <nombre> — buscar y agregar una serie",
    "/library [filtro] — ver la biblioteca (películas y series)",
    "/queue — descargas en curso",
    "/upcoming [días] — próximos estrenos y episodios (default 30)",
    "/language es|en — cambiar idioma",
    "/clear — cancelar la operación en curso",
    "/help — esta ayuda",
  ].join("\n"),
  helpAdmin: [
    "",
    "*Admin:*",
    "/rss — sync RSS en ambos servicios",
    "/wanted — buscar todo lo faltante",
    "/refresh — refrescar bibliotecas",
    "/remove <nombre> — eliminar de la biblioteca",
    "/users — usuarios autorizados",
    "/revoke — revocar un usuario",
    "/unrevoke — restaurar un usuario",
    "/cid — ID de este chat",
  ].join("\n"),
  cid: (id) => `ID de este chat: \`${id}\``,
  cleared: "❌ Operación cancelada.",
  sonarrMissing: "Sonarr no está configurado.",
  movieUsage: "Uso: /movie <nombre de la película>",
  serieUsage: "Uso: /serie <nombre de la serie>",
  removeUsage: "Uso: /remove <nombre>",
  removeWho: "¿Cuál eliminar?",
  removeConfirm: (name) => `¿Eliminar "${name}" de la biblioteca?`,
  removeFiles: "¿Borrar también los archivos del disco?",
  removed: (name) => `🗑 "${name}" eliminada.`,
  noResults: (term) => `No encontré nada para "${term}".`,
  alreadyAdded: (title) => `"${title}" ya está en la biblioteca.`,
  serieExists: (title) => `"${title}" ya está en la biblioteca. Elige una temporada para monitorear y buscar:`,
  seasonDone: (n) => `📺 ✅ Temporada ${n} monitoreada y buscándose.`,
  specials: "Especiales",
  pickProfile: "Elige el perfil de calidad:",
  pickFolder: "Elige la carpeta de destino:",
  pickMonitor: "¿Qué temporadas monitorear?",
  searchNow: "¿Buscar y descargar ahora?",
  added: (icon, title) => `${icon} ✅ "${title}" agregada. ¡Listo!`,
  yes: "✔️ Sí",
  no: "✖️ No",
  cancel: "❌ Cancelar",
  addThis: "✅ Agregar",
  usersTitle: "Usuarios autorizados:",
  noUsers: "No hay usuarios autorizados.",
  noRevoked: "No hay usuarios revocados.",
  revokeWho: "¿A quién revocar?",
  unrevokeWho: "¿A quién restaurar?",
  confirmRevoke: (name) => `¿Revocar el acceso de ${name}?`,
  confirmUnrevoke: (name) => `¿Restaurar el acceso de ${name}?`,
  revoked: (name) => `Acceso de ${name} revocado.`,
  unrevoked: (name) => `Acceso de ${name} restaurado.`,
  userNotFound: "usuario no encontrado",
  commandsSent: (list) => `✅ Comandos enviados:\n${list.join("\n")}`,
  libraryEmpty: "La biblioteca está vacía (o nada coincide con el filtro).",
  queueEmpty: "No hay descargas en curso.",
  calendarEmpty: "Nada programado en ese rango.",
  error: (msg) => `⚠️ Error: ${msg}`,
  langUsage: (current) => `Uso: /language es|en — idioma actual: ${current}`,
  langSet: "✅ Idioma cambiado a español.",
  monitorAll: "Todas las temporadas",
  monitorFuture: "Solo temporadas futuras",
  monitorFirst: "Primera temporada",
  monitorLast: "Última temporada",
};

export const en = {
  locale: "en",
  notYourMenu: "⛔ This menu belongs to someone else.",
  notAuthorized: "🚫 You're not authorized. Use /auth <password> to request access.",
  adminOnly: "🚫 Only the admin can use this command.",
  authAlready: "You're already authorized. Use /help to see the commands.",
  authRevoked: "Your access was revoked. Talk to the admin.",
  authBadPassword: "Wrong password.",
  authGranted: "✅ Access granted. Use /help to see the commands.",
  authUsage: "Usage: /auth <password>",
  authUserGranted: (name) => `User ${name} now has access to the bot.`,
  notifAvailable: (icon, title) => `${icon} ✅ ${title} is now available`,
  notifEpisodes: (title, n, list) => `📺 ✅ ${title} — ${n} new episode(s): ${list}`,
  help: [
    "🎬 /movie <name> — search and add a movie",
    "📺 /serie <name> — search and add a series",
    "/library [filter] — browse the library (movies and series)",
    "/queue — current downloads",
    "/upcoming [days] — upcoming releases and episodes (default 30)",
    "/language es|en — change language",
    "/clear — cancel the current operation",
    "/help — this help",
  ].join("\n"),
  helpAdmin: [
    "",
    "*Admin:*",
    "/rss — RSS sync on both services",
    "/wanted — search all missing items",
    "/refresh — refresh libraries",
    "/remove <name> — remove from the library",
    "/users — authorized users",
    "/revoke — revoke a user",
    "/unrevoke — restore a user",
    "/cid — this chat's ID",
  ].join("\n"),
  cid: (id) => `This chat's ID: \`${id}\``,
  cleared: "❌ Operation cancelled.",
  sonarrMissing: "Sonarr is not configured.",
  movieUsage: "Usage: /movie <movie name>",
  serieUsage: "Usage: /serie <series name>",
  removeUsage: "Usage: /remove <name>",
  removeWho: "Which one should be removed?",
  removeConfirm: (name) => `Remove "${name}" from the library?`,
  removeFiles: "Also delete the files from disk?",
  removed: (name) => `🗑 "${name}" removed.`,
  noResults: (term) => `Nothing found for "${term}".`,
  alreadyAdded: (title) => `"${title}" is already in the library.`,
  serieExists: (title) => `"${title}" is already in the library. Pick a season to monitor and search:`,
  seasonDone: (n) => `📺 ✅ Season ${n} is now monitored and searching.`,
  specials: "Specials",
  pickProfile: "Pick a quality profile:",
  pickFolder: "Pick a destination folder:",
  pickMonitor: "Which seasons should be monitored?",
  searchNow: "Search and download now?",
  added: (icon, title) => `${icon} ✅ "${title}" added. Done!`,
  yes: "✔️ Yes",
  no: "✖️ No",
  cancel: "❌ Cancel",
  addThis: "✅ Add",
  usersTitle: "Authorized users:",
  noUsers: "There are no authorized users.",
  noRevoked: "There are no revoked users.",
  revokeWho: "Whose access should be revoked?",
  unrevokeWho: "Whose access should be restored?",
  confirmRevoke: (name) => `Revoke ${name}'s access?`,
  confirmUnrevoke: (name) => `Restore ${name}'s access?`,
  revoked: (name) => `${name}'s access revoked.`,
  unrevoked: (name) => `${name}'s access restored.`,
  userNotFound: "user not found",
  commandsSent: (list) => `✅ Commands sent:\n${list.join("\n")}`,
  libraryEmpty: "The library is empty (or nothing matches the filter).",
  queueEmpty: "No downloads in progress.",
  calendarEmpty: "Nothing scheduled in that range.",
  error: (msg) => `⚠️ Error: ${msg}`,
  langUsage: (current) => `Usage: /language es|en — current language: ${current}`,
  langSet: "✅ Language set to English.",
  monitorAll: "All seasons",
  monitorFuture: "Future seasons only",
  monitorFirst: "First season",
  monitorLast: "Last season",
};
